---
- name: Backup Immich PostgreSQL database to NAS
  hosts: immich_host
  become: true
  vars:
    container_name: "immich_postgres"
    db_user: "postgres"   # Change if different in stack.env
    backup_dir: "/mnt/NASGuido_photo/Immich_DB_Backup"
    keep_days: 14

  tasks:
    - name: Check if NAS backup directory exists
      stat:
        path: "{{ backup_dir }}"
      register: backup_dir_stat
    
    - name: Fail if NAS backup directory is missing or inaccessible
      fail:
        msg: "Backup directory {{ backup_dir }} is not present or not accessible. Check NAS mount."
      when: not backup_dir_stat.stat.exists or not backup_dir_stat.stat.isdir    

    - name: Run pg_dumpall inside container and gzip to NAS
      shell: >
        docker exec -t {{ container_name }}
        pg_dumpall --clean --if-exists --username={{ db_user }}
        | gzip > {{ backup_dir }}/dump_$(date +%F_%H-%M).sql.gz
      args:
        executable: /bin/bash

    - name: Remove backups older than {{ keep_days }} days
      find:
        paths: "{{ backup_dir }}"
        patterns: "*.sql.gz"
        age: "{{ keep_days }}d"
      register: old_backups

    - name: Delete old backups
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_backups.files }}"
      when: old_backups.matched > 0
