- name: Install or update Komodo Periphery with checksum validation
  hosts: all
  become: true

  vars:
    periphery_installer_url: "https://raw.githubusercontent.com/moghtech/komodo/main/scripts/setup-periphery.py"
    periphery_installer_path: "/tmp/setup-periphery.py"

  tasks:
    - name: Ensure Python3 is installed
      ansible.builtin.package:
        name: python3
        state: present

    - name: Check if periphery is already installed
      ansible.builtin.command: /usr/local/bin/periphery --version
      register: periphery_current_version
      ignore_errors: yes
      changed_when: false

    - name: Stat current installer if exists
      ansible.builtin.stat:
        path: "{{ periphery_installer_path }}"
        checksum_algorithm: sha256
      register: existing_script

    - name: Download latest installer
      ansible.builtin.get_url:
        url: "{{ periphery_installer_url }}"
        dest: "{{ periphery_installer_path }}"
        mode: '0755'
        checksum_algorithm: sha256
      register: new_script

    - name: Run installer if script changed or periphery not installed
      ansible.builtin.command: "python3 {{ periphery_installer_path }}"
      when: existing_script.stat.checksum is not defined or
            existing_script.stat.checksum != new_script.checksum or
            periphery_current_version.stdout is not defined
      notify: Restart periphery service

    - name: Ensure periphery service is enabled
      ansible.builtin.systemd:
        name: periphery
        enabled: yes

  handlers:
    - name: Restart periphery service
      ansible.builtin.systemd:
        name: periphery
        state: restarted
        daemon_reload: yes
