---
- name: Update Ubuntu Server VMs
  hosts: ubuntu_vms
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_cache_update
      
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: apt_upgrade_result
      
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      
    - name: Reboot server if required
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 5
      when: reboot_required_file.stat.exists
      
    - name: Verify SSH connectivity after reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
