- name: Update Ubuntu Server VMs
  hosts: ubuntu_vms
  serial: 1
  become: true
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_command_timeout: 3600
    # Reduce SSH timeouts to handle connection loss better
    ansible_ssh_common_args: '-o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o ConnectTimeout=10'
  
  pre_tasks:
    - name: Show current SSH user
      debug:
        msg: Connected as {{ ansible_user_id }}
    
    - name: Wait for apt/dpkg locks to be released
      shell: |
        timeout=300
        elapsed=0
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
              fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
              fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "APT lock detected. Waiting..."
          sleep 10
          elapsed=$((elapsed + 10))
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout waiting for APT locks after ${timeout}s"
            exit 1
          fi
        done
      changed_when: false
    
    - name: Ensure sudo access
      assert:
        that:
          - ansible_user_id == 'root'
        fail_msg: Playbook must be run with sudo privileges.
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      register: apt_cache_update
      timeout: 300
    
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: "force-confdef,force-confold"
      register: apt_upgrade_result
    
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    
    - name: Display reboot requirement status
      debug:
        msg: "Reboot required: {{ reboot_required.stat.exists }}"
    
    - name: Log reboot start time
      command: date "+%Y-%m-%d %H:%M:%S"
      register: reboot_start
      when: reboot_required.stat.exists
      changed_when: false
    
    - block:
        - name: Trigger reboot using shell command
          shell: 'sleep 2 && shutdown -r now "Ansible reboot"'
          async: 1
          poll: 0
          when: reboot_required.stat.exists
        
        - name: Wait for system to go down
          wait_for_connection:
            delay: 5
            timeout: 60
          ignore_errors: yes
          when: reboot_required.stat.exists
        
        - name: Wait for system to come back up
          wait_for_connection:
            delay: 30
            sleep: 10
            timeout: 600
          when: reboot_required.stat.exists
        
        - name: Wait for system to be fully ready
          shell: uptime
          register: uptime_output
          retries: 10
          delay: 10
          until: uptime_output.rc == 0
          when: reboot_required.stat.exists
      
      rescue:
        - name: Log reboot issue
          debug:
            msg: "Encountered issue during reboot, attempting recovery..."
        
        - name: Final wait for connection
          wait_for_connection:
            delay: 10
            timeout: 300
    
    - name: Log reboot end time
      command: date "+%Y-%m-%d %H:%M:%S"
      register: reboot_end
      when: reboot_required.stat.exists
      changed_when: false
    
    - name: Show reboot duration
      debug:
        msg: >
          Host {{ inventory_hostname }} rebooted in {{
            ( (reboot_end.stdout | to_datetime('%Y-%m-%d %H:%M:%S')) -
              (reboot_start.stdout | to_datetime('%Y-%m-%d %H:%M:%S'))
            ).total_seconds() | int
          }} seconds.
      when: reboot_required.stat.exists and reboot_end.stdout is defined
    
    - name: Verify system is responsive
      command: uptime
      changed_when: false
      register: uptime_check
    
    - name: Show system uptime
      debug:
        msg: "{{ uptime_check.stdout }}"

- name: Continue with remaining hosts
  hosts: ubuntu_vms
  serial: 1
  become: true
  gather_facts: no
  tasks:
    - name: Final health check
      ping:
