---
- name: Update Ubuntu Server VMs
  hosts: ubuntu_vms
  become: true
  become_method: sudo
  gather_facts: yes

  pre_tasks:
     - name: Show current SSH user
       debug:
        msg: "Connected as {{ ansible_user_id }}"

    - name: Wait for apt/dpkg locks to be released
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
              fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || \
              fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "APT lock detected. Waiting..."
          sleep 10
        done
      changed_when: false
    - name: Ensure sudo access
      assert:
        that:
          - ansible_user_id == 'root'
        fail_msg: "Playbook must be run with sudo privileges."


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
      become_method: sudo
      register: apt_cache_update

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      become: true
      become_method: sudo      
      register: apt_upgrade_result

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot server if required
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 5
      when: reboot_required_file.stat.exists

    - name: Verify SSH connectivity after reboot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
